# Generated by Django 3.0.10 on 2020-10-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0061_auto_20190820_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='language',
            field=models.CharField(blank=True, choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('en-NZ', 'New Zealand English')], default='mi', help_text='Language for a particular recording', max_length=16, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='language',
            field=models.CharField(choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('en-NZ', 'New Zealand English')], default='mi', max_length=16),
        ),
        migrations.AlterField(
            model_name='text',
            name='primary_language',
            field=models.CharField(choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('en-NZ', 'New Zealand English')], default='mi', max_length=16, verbose_name='primary language'),
        ),
        migrations.AlterField(
            model_name='text',
            name='secondary_language',
            field=models.CharField(blank=True, choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('en-NZ', 'New Zealand English')], max_length=16, null=True, verbose_name='secondary language'),
        ),
    ]
