# Generated by Django 3.0.10 on 2020-10-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('corpus', '0062_auto_20201009_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='language',
            field=models.CharField(blank=True, choices=[('mi', 'Māori'), ('haw', 'Hawaiian'), ('rar', 'Cook Island Māori'), ('en-NZ', 'New Zealand English')], default='mi', help_text='Language for a particular recording', max_length=16, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='recordingqualitycontrol',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, help_text='Model to which this QualityControl refers. This should be         the content type ID. Implemented types are Recordings (id=8),        Sentences (id=10), Transcription Segments (id=24).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='recordingqualitycontrol',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='language',
            field=models.CharField(choices=[('mi', 'Māori'), ('haw', 'Hawaiian'), ('rar', 'Cook Island Māori'), ('en-NZ', 'New Zealand English')], default='mi', max_length=16),
        ),
        migrations.AlterField(
            model_name='text',
            name='primary_language',
            field=models.CharField(choices=[('mi', 'Māori'), ('haw', 'Hawaiian'), ('rar', 'Cook Island Māori'), ('en-NZ', 'New Zealand English')], default='mi', max_length=16, verbose_name='primary language'),
        ),
        migrations.AlterField(
            model_name='text',
            name='secondary_language',
            field=models.CharField(blank=True, choices=[('mi', 'Māori'), ('haw', 'Hawaiian'), ('rar', 'Cook Island Māori'), ('en-NZ', 'New Zealand English')], max_length=16, null=True, verbose_name='secondary language'),
        ),
    ]
