# Generated by Django 3.1.2 on 2020-10-22 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0063_auto_20201022_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingqualitycontrol',
            name='pronunciation',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='RecordingMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='corpus.recording')),
            ],
        ),
    ]
