# Generated by Django 3.1.3 on 2020-11-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0064_auto_20201022_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingqualitycontrol',
            name='recording',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_control', to='corpus.recording'),
        ),
    ]
