---

git_repo: https://github.com/TeHikuMedia/corpora.git
project_name: corpora
application_name: corpora
django_settings_folder: "{{application_name}}"
ssl_dest_dir: /etc/ssl

timezone: Pacific/Auckland
rebuild_database: no
destroy_vagrant: no
maintenance: no
purge_celery_tasks: no

# Application settings.
virtualenv_path: "/webapp"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_path: "{{ project_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
application_run_dir: "{{ virtualenv_path }}/run"
daphne_log_file: "{{ application_log_dir }}/daphne_supervisor.log"
django_log_file: "{{ application_log_dir }}/django.log"
celery_log_file: "{{ application_log_dir }}/celery.log"
requirements_file: "{{ project_path }}/requirements.txt"
application_tmp_dir: "/tmp/{{ project_name }}_files"
npm_dir: "{{application_path}}/vue_frontend"
npm_build_cmd: "npm run build"