---

- name: Get the RDS details when ec2_database isn't properly defined
  sudo: no
  local_action:
    module: rds
    command: facts
    region: ap-southeast-2
    instance_name: "{{project_name}}-{{env_type}}-database"
  register: ec2_database

- debug: var=ec2_database


- debug: var=ec2_database

- name: check if ec2_database variable is proper
  when: ec2_database is defined
  command: echo {{ ec2_database.instance }}
  ignore_errors: yes
  register: command_result
  tags: rds
- debug: var=command_result
- debug: var=ec2_database


- name: Get RDS facts
  when: "{{ ec2_database is not defined or command_result.stderr != '' }}"
  include: get_rds_facts.yml
  tags: rds
- debug: var=ec2_database

- name: Dummmy
  command: echo {{ ec2_database = {'instance':{'endpoint':'localhost'} } if ec2_database['skipped']='true' else  ec2_database  }}
- debug: var=ec2_database
