# Generated by Django 3.0.10 on 2020-10-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_auto_20190820_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='language',
            field=models.CharField(choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('en-NZ', 'New Zealand English')], default='mi', max_length=16, unique=True, verbose_name='language'),
        ),
    ]
