# Generated by Django 3.0.10 on 2020-10-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0055_auto_20190820_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='receive_emails',
            field=models.BooleanField(default=True, help_text='Check to receive occasional emails from us.'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='language',
            field=models.CharField(choices=[('mi', 'Maori'), ('haw', 'Hawaiian'), ('en-NZ', 'New Zealand English')], max_length=16, verbose_name='language'),
        ),
    ]
