# Generated by Django 3.0.10 on 2020-10-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0056_auto_20201009_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownlanguage',
            name='language',
            field=models.CharField(choices=[('mi', 'Māori'), ('haw', 'Hawaiian'), ('rar', 'Cook Island Māori'), ('en-NZ', 'New Zealand English')], max_length=16, verbose_name='language'),
        ),
    ]
