---

### THERE AREN'T NEEDED AS CELERY HAPPENS IN DEPLOYMENT AND AFTER THE WEB ROLE ###
#server_root_dir: "/webapp"
#virtualenv_path: "{{ server_root_dir }}/myapp"
#application_path: "{{ server_root_dir }}/myapp/project_dir/app_dir"

# Taken from main.yml at web/vars
#virtualenv_path: "/webapp"
#project_path: "{{ virtualenv_path }}/{{ project_name }}"
#application_path: "{{ project_path }}/{{ application_name }}"
#######################################

setup_monitor: yes

celery_user: "{{ application_name }}"
celery_group: webapp

celery_application_name: celery
flower_application_name: flower
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_template_file: "{{ celery_application_name }}_start.j2"
flower_template_file: "{{ flower_application_name }}_start.j2"

