# Tasks for creating security groups
# We use the same sg as the webserver for now

# Tasks for launching instances
# What happens if instance already exists? I'm assuming the exact_count = 1 fixes this...
# If an instance is stopped, these will launch new ones. Should they start existing ones?
- name: Launch media tasks instance
  local_action:
    module: ec2
    region: ap-southeast-2
    keypair: "{{ ec2_key_pair }}"
    group: "{{ project_name }}-{{env_type}}-webserver"
    instance_type: "{{ mediatasks_instance_type }}"
    image:  "{{ webserver_ami }}" # use same AMI as webserver
    wait: yes
    instance_tags:
      env_server_type: "{{env_type}}_media"
    exact_count: 1
    count_tag: 
      env_server_type: "{{env_type}}_media"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 32
  register: ec2_mediatasks

# Tasks for tagging and grouping launched instances
- name: Tag instance
  local_action: ec2_tag resource={{ item.id }} region=ap-southeast-2 state=present
  with_items: ec2_mediatasks.tagged_instances 
  args:
    tags:
      Name: "{{project_name}}-{{env_type}}-mediaserver"
      env_type: "{{env_type}}"
      server_type: "media"
      app: "{{env_type}}"
