---

- name: Get the RDS details when ec2_database isn't properly defined
  sudo: no
  local_action:
    module: rds
    command: facts
    region: ap-southeast-2
    instance_name: "{{project_name}}-{{env_type}}-database"
  register: ec2_database

- debug: var=ec2_database