---

- include: get_ec2_facts.yml
  when: env_type != 'local'

- set_fact:
    server_role: "primary"
  when: env_type == 'local'
  tags:
    django-celery

- include_tasks: setup_git_repo.yml
  when: ansible_env.PWD != "/home/vagrant" # in vagrant we mirror our local repository, so it's not necessary to set up the bitbucket repo

- include_tasks: setup_virtualenv.yml

- include_tasks: setup_supervisor.yml
  tags:
    - server
    - sites

- include_tasks: install_bower.yml

- include_tasks: setup_django_app.yml
  tags:
    - server
    - django-server
    - django
    - django-celery

- include_tasks: setup_nginx.yml
  tags: 
    - server
    - sites

- include_tasks:  nginx_secure_dev_site.yml
  tags: 
    - server
    - sites
  when: env_type == 'stag'

# still need to call nginx restart!

