---

#- include_tasks: get_rds_facts.yml

- name: Install boto3
  pip:
    name: boto3
    state: present

- local_action: ec2_instance_facts
  become: no
  args:
    aws_access_key: "{{ansible_aws_id}}"
    aws_secret_key: "{{ansible_aws_secret}}"
    region: "{{aws_region}}"
    filters:
      "tag:Name": "{{project_name}}-{{env_type}}-webserver"
      "tag:server_type": "web"
      "ip-address": "{{inventory_hostname}}"
  register:
    ec2_webserver_facts
  when: env_type != 'local'
  tags:
    django-celery

- set_fact:
    ec2_webserver: "{{ec2_webserver_facts.instances[0]}}"
  when: env_type != 'local'
  tags:
    django-celery  

- set_fact:
    server_role: "{{ ec2_webserver.tags['server_role'] }}"
  when: env_type != 'local'
  tags:
    django-celery

- set_fact:
    server_role: "primary"
  when: env_type == 'local'
  tags:
    django-celery


- include_tasks: create_users_and_groups.yml


- include_tasks: setup_git_repo.yml
  when: ansible_env.PWD != "/home/vagrant" # in vagrant we mirror our local repository, so it's not necessary to set up the bitbucket repo

- include_tasks: setup_virtualenv.yml

- include_tasks: setup_supervisor.yml
  tags:
    - server
    - sites


- include_tasks: install_bower.yml

- include_tasks: install_thirdparty_files.yml
  tags:
    - fontawesome

- include_tasks: setup_django_app.yml
  tags:
    - server
    - django-server
    - django
    - django-celery

- include_tasks: set_file_permissions.yml

- include_tasks: setup_nginx.yml
  tags: 
    - server
    - sites

- include_tasks: nginx_secure_dev_site.yml
  tags: 
    - server
    - sites

