---

- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate
  tags:
    - sites

- name: Create the Gunicorn script file
  template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start_{{item}}
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=yes
  tags:
    - sites
  loop: "{{django_settings}}"
  loop_control:
    index_var: item_index
  notify:
    - restart application

- name: Create the gunicorn run folder
  file: path={{ virtualenv_path }}/run/
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0755
        state=directory

- name: Clear old confs
  shell: rm -rf /etc/supervisor/conf.d/*

- name: Clear old confs
  shell: rm -rf /etc/supervisor/conf.d/*

- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}_{{item}}.conf
            backup=yes
  tags:
    - sites
  loop: "{{django_settings}}"
  loop_control:
    index_var: item_index
  notify:
    - reload supervisor
    - restart all

- name: Setup notebook supervisor config
  template: src=supervisor_notebook_config.j2
            dest=/etc/supervisor/conf.d/notebook.conf
            backup=yes
  tags:
    - sites
  notify:
    - reload supervisor
    - restart all
