---

- name: Install mercurial so we can retrieve app source
  apt: name=mercurial state=latest
  become: true

- name: Install known_hosts file for BitBucket repository
  copy:
    src: known_hosts
    dest: "/home/{{ansible_user}}/.ssh/known_hosts"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: Install private deploy key file for BitBucket repository
  copy:
    content: "{{ bitbucket_deploy_private_key }}" 
    dest: "/home/{{ansible_user}}/.ssh/id_rsa"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "600"

- name: make repo directory
  become: true
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ ansible_user }}
        group={{ gunicorn_group }}
        state=directory
  tags:
   - bitbucket

- name: Setup the Bitbucket repo
  # the private key is stored in admin's .ssh
  sudo: no 
  hg:   repo="{{ bitbucket_repo }}" 
        dest="{{ project_path }}" 
        revision="{{ bitbucket_branch }}"
  when: setup_bitbucket_repo
  tags: bitbucket
  notify:
   - destroy media server ami
   - destroy media server ami 2
   - destroy media server ami 3
   
#- name: make repo directory
#  sudo: yes
#  file: path={{ virtualenv_path }}
#        recurse=yes
#        owner={{ gunicorn_user }}
#        group={{ gunicorn_group }}
#        state=directory
#  tags:
#   - bitbucket

#- name: CD to destination directory
#  command: cd {{ virtualenv_path }}
#  tags: bitbucket

#- name: Clone repo
#  command: hg clone ssh://hg@bitbucket.org/tehiku/{{project_name}} -r {{ bitbucket_branch }}
#  tags: bitbucket