---

- name: Create the celery log folder
  file: path={{ application_log_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        mode=0774
        state=directory

- name: Create the celery log file
  file: path={{ application_log_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=touch
        mode=0755
  become: yes

- name: Create the application bin folder
  file: path={{virtualenv_path}}/bin
        state=directory

- name: LOCAL Create the virtualenv postactivate script to set environment variables
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0777
            backup=yes
  with_items:
    - 127.0.0.1
  when: env_type == 'local'

- name: Set dummy variable for local deployment
  set_fact:
    ec2_webserver: {'private_ip_address':127.0.0.1}
  when: env_type == 'local'


- name: REMOTE Create the virtualenv postactivate script to set environment variables
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes
  when: env_type != 'local'
  with_items:
    - "{{ec2_webserver.private_ip_address}}"
