- name: Install ffmpeg codecs & their dependencies
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - libx264-dev
    - libmp3lame-dev
    - libopus-dev
    - libtool
  tags: 
    - ffmpeg
    - packages  


- name: Install h265
  hg: repo="https://bitbucket.org/multicoreware/x265" dest="{{ ffmpeg_sources_dir }}/x265" 
- shell: PATH="$HOME/bin:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DENABLE_SHARED:bool=off ../../source
  args:
    chdir: "{{ffmpeg_sources_dir}}/x265/build/linux"
- shell: "{{item}}"
  args:
    chdir: "{{ffmpeg_sources_dir}}/x265/build/linux"
  with_items:
    - make
    - "make install"


- name: Install libfdk-aac
  file: path="{{ffmpeg_sources_dir}}/fdk-aac" state=directory
- get_url: url={{fdk_aac_source_file}} dest="{{ffmpeg_sources_dir}}/fdk-aac/fdk-aac.tar.gz"
- shell: "{{item}}"
  args:
    chdir: "{{ffmpeg_sources_dir}}/fdk-aac/"
  with_items:
    - "tar xzvf {{ffmpeg_sources_dir}}/fdk-aac/fdk-aac.tar.gz -C {{ffmpeg_sources_dir}}/fdk-aac --strip-components=1"
    - "autoreconf -fiv"
    - "./configure --prefix=\"$HOME/ffmpeg_build\" --disable-shared"
    - make
    - "make install"

# cd ~/ffmpeg_sources
# wget -O fdk-aac.tar.gz https://github.com/mstorsjo/fdk-aac/tarball/master
# tar xzvf fdk-aac.tar.gz
# cd mstorsjo-fdk-aac*
# autoreconf -fiv
# ./configure --prefix="$HOME/ffmpeg_build" --disable-shared
# make
# make install
# make distclean

- name: Install libvpx
  file: path="{{ffmpeg_sources_dir}}/libvpx" state=directory
- get_url: url={{ libvpx_source_file }} dest="{{ffmpeg_sources_dir}}/libvpx/libvpx.tar.bz2"
- shell: "{{item}}"
  args:
    chdir: "{{ffmpeg_sources_dir}}/libvpx"
  with_items:
    - "tar xjvf {{ffmpeg_sources_dir}}/libvpx/libvpx.tar.bz2 -C {{ffmpeg_sources_dir}}/libvpx --strip-components=1"
    - "PATH=\"$HOME/bin:$PATH\" ./configure --prefix=\"$HOME/ffmpeg_build\" --disable-examples --disable-unit-tests"
    - "PATH=\"$HOME/bin:$PATH\" make"
    - "make install"

# cd ~/ffmpeg_sources
# wget http://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.5.0.tar.bz2
# tar xjvf libvpx-1.5.0.tar.bz2
# cd libvpx-1.5.0
# PATH="$HOME/bin:$PATH" ./configure --prefix="$HOME/ffmpeg_build" --disable-examples --disable-unit-tests
# PATH="$HOME/bin:$PATH" make
# make install
# make clean