---

# UPGARDES
# We need to be cautious about upgrades as they can break everything and cause headaches
# It's almost as if they best way to upgrade is to relaunch an instance from scratch
# upon building it will use the latest packages. Then we can still use the ansible scripts to
# deploy updates to code.

# - name: Do a safe upgrade
#   apt: upgrade=safe update_cache={{ update_apt_cache }}
#   tags: upgrade

- name: Ensure OpenSSl and libssl are the latest versions
  apt: 
    update_cache: "{{ update_apt_cache }}"
    state: latest
    name:
      - openssl
      - libssl-dev
      - libssl-doc
  tags: packages

- name: Install base packages
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    name:
      - build-essential
      - mercurial
      - cmake
      - yasm
      - autoconf
      - automake
      - python3
      - python3-dev
      - python3-pip
      - python3-pycurl
      - supervisor
      - libjpeg-dev
      - libxml2-dev
      - libxslt-dev
      - ntp
      - ca-certificates
      - ruby
      - git
      - gettext
      - ruby-sass
      - dbus
      - unzip
      - curl
      - ffmpeg
      - apache2-utils
      - python-passlib
  tags: packages
    # - ntpdate
    # - ca-certificates
    # - libffi-dev # needed to build pip cryptography
