---

- local_action: ec2_instance_facts
  become: no
  args:
    aws_access_key: "{{ansible_aws_id}}"
    aws_secret_key: "{{ansible_aws_secret}}"
    region: ap-southeast-2
    filters:
      "tag:project_env_server_type_role": "{{ project_name }}_{{env_type}}_{{server_type}}_{{server_role}}" 
  register:
    ec2_facts
- set_fact:
    ec2_server: "{{ec2_facts.instances[0]}}"

- name: Ensure ec2 is stopped
  ec2:
    instance_ids: "{{ec2_server.instance_id}}"
    region: ap-southeast-2
    state: stopped
    wait: yes
    wait_timeout: 500