---

# SSH Credentials
private_key: ~/.ssh/corpora_2020.pem

# Repository Details
branch: "master"

certificate_domain_name:  koreromaori.com
zone_domain_name: koreromaori.com
domain_name: koreromaori.com
cloudfront_subdomain: cdn
cloudfront_cname: "{{cloudfront_subdomain}}.{{zone_domain_name}}"


# Shared Roles Config
asg_desired: 1
asg_min_size: 1
asg_max_size: 10

asg_mixed_instances_policy:
  instance_types:
    - t3.medium
    - t3.large
    - t3.xlarge
    - t3.2xlarge
