---

# SSH Credentials
private_key: ~/.ssh/corpora_2020.pem

# Repository Details
branch: "staging"

certificate_domain_name: dev.koreromaori.com
zone_domain_name: koreromaori.com
domain_name: dev.koreromaori.com
cloudfront_subdomain: staticdev
cloudfront_cname: "{{cloudfront_subdomain}}.{{zone_domain_name}}"


# Shared Roles Config
asg_desired: 1
asg_min_size: 1
asg_max_size: 3

asg_mixed_instances_policy:
  instance_types:
    - t3.small
    - t3.medium
    - t3.large
