---

- include: get_rds_facts.yml

- include: rds_database.yml
  when: inventory_hostname != 'default'
  tags:
    - rds
    - database
    - remote
    - provision

- name: delete database variable
  command: echo undefined
  register: ec2_database