---

- name: Create the ASG Policy for Decreasing Instances
  local_action:
    module: ec2_scaling_policy
    name: "ASG-ScaleDOWNPolicy-{{ project_name }}-{{server_type}}"
    state: present
    region: "{{aws_region}}"
    adjustment_type: "ChangeInCapacity"
    asg_name: "ASG-{{ project_name }}-{{env_type}}-{{server_type}}"
    scaling_adjustment: -1
    min_adjustment_step: 1
    cooldown: 120
  register: ec2_scaling_policy_down
  tags:
    - ec2
    - scaling
    - policy

- name: Create the ASG Policy for Increasing Instances
  local_action:
    module: ec2_scaling_policy
    name: "ASG-ScaleUPPolicy-{{ project_name }}-{{server_type}}"
    state: present
    region: "{{ aws_region }}"
    adjustment_type: "ChangeInCapacity"
    asg_name: "ASG-{{ project_name }}-{{env_type}}-{{server_type}}"
    scaling_adjustment: 1
    min_adjustment_step: 1
    cooldown: 120
  register: ec2_scaling_policy_up
  tags:
    - ec2
    - scaling
    - policy
