---

- name: Delete the ASG with the LC
  local_action:
    module: ec2_asg
    name: "ASG-{{ project_name }}-{{env_type}}-{{server_type}}"
    launch_config_name: "LC-{{ project_name }}-{{env_type}}-{{server_type}}"
    state: absent
    region: "{{aws_region}}"  
  register: ec2_asg
  async: 600
  poll: 10

- name: Delete the Launch Configurations
  local_action:
    module: ec2_lc
    name: "LC-{{ project_name }}-{{env_type}}-{{server_type}}"
    state: absent # what happens if it's already present... can we overwrite it?
    region: "{{aws_region}}"  
    instance_type: "{{webserver_instance_type}}"
  register: ec2_lc