---

# - name: Gather facts
#   action: ec2_metadata_facts
#   when: env_type !='local'

# - local_action: ec2_instance_info
#   become: no
#   args:
#     aws_access_key: "{{ansible_aws_id}}"
#     aws_secret_key: "{{ansible_aws_secret}}"
#     region: ap-southeast-2
#     filters:
#       "tag:Name": "{{ webserver_name }}"
#       "tag:server_type": "web"
#   register:
#     ec2_info
#   when: env_type !='local'

# - set_fact:
#     ec2_server: "{{ec2_info.instances[0]}}"
#   when: env_type !='local'

- include: copy_scripts.yml

- include: setup_supervisor.yml

- name: Check running applications managed by supervisor
  shell: supervisorctl status
  register: supervisor_applications
  tags:
    - celery
    - flower
    - deploy

- name: Restart the {{ celery_application_name }} app
  supervisorctl: name="{{ celery_application_name }}-{{item}}" state=restarted
  when: supervisor_applications.stdout.find(celery_application_name) != -1
  with_items:
    - celery
    - beat
    # - django-beat
  tags:
    - celery
    - deploy
  ignore_errors: True

- name: Restart the {{ flower_application_name }} app
  supervisorctl: name={{ flower_application_name }} state=restarted
  when: supervisor_applications.stdout.find(flower_application_name) != -1
  tags:
    - flower
    - deploy
