Type: AWS::CloudWatch::Alarm
Properties:
  ActionsEnabled: True
  AlarmActions:
    - String (ARN - add an instance stepwise)
  AlarmDescription: This will alarm when high traffic
  AlarmName: HIGH-Requests-Alarm-{{ project_name }}-{{env_type}}
  ComparisonOperator: ">"
  Dimensions:
    LoadBalancer: 'app/ELB-LB-{{ project_name }}-{{env_type}}-web/{{elb_id}}'
    TargetGroup: 'targetgroup/ELB-TG-{{ project_name }}-{{env_type}}-web/{{tg_id}}'
  EvaluationPeriods: 2
  MetricName: RequestCount
  Namespace: AWS/ApplicationELB
  OKActions:
    - String (ARN - remove an instance)
  Period: 60
  Statistic: Sum
  Threshold: 50.0
  TreatMissingData: String
  Unit: Count



