name: Build staging vue client

on:
  pull_request:
    branches:
      - tumu
      - staging
    paths:
      - "corpora/vue_frontend/**"

jobs:

  build-vue-client:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - uses: aws-actions/amazon-ecr-login@v1

    - name: Build deploy docker
      run: docker build ./corpora-deploy -t corpora-deploy --file ./corpora-deploy/gitactions.Dockerfile

    - name: Deploy vue files on pull request
      if: ${{ github.head_ref != null }}
      env:
        BRANCH: ${{ github.head_ref }}
        DOCKER_IMAGE: corpora-deploy
      run: |
        docker run --entrypoint /deploy/scripts/deploy.sh \
        -e ENV_TYPE=staging -e TAGS=webpack -e BRANCH=$BRANCH \
        -e ANSIBLE_VAULT_PASS=${{secrets.ANSIBLE_VAULT_PASS}} $DOCKER_IMAGE

    - name: Deploy vue files for staging
      if: ${{ github.head_ref == null }}
      env:
        BRANCH: staging
        DOCKER_IMAGE: corpora-deploy
      run: |
        docker run --entrypoint /deploy/scripts/deploy.sh \
        -e ENV_TYPE=staging -e TAGS=webpack -e BRANCH=$BRANCH \
        -e ANSIBLE_VAULT_PASS=${{secrets.ANSIBLE_VAULT_PASS}} $DOCKER_IMAGE
