name: Build production vue client

on:
  push:
    branches:
      - tumu
    paths:
      - "corpora/vue_frontend/**"

jobs:

  build-vue-client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - uses: aws-actions/amazon-ecr-login@v1

    - name: Build deploy docker
      run: |
        docker build ./corpora-deploy -t corpora-deploy --file ./corpora-deploy/gitactions.Dockerfile

    - name: Build vue files
      run: |
        docker run --entrypoint /deploy/scripts/deploy.sh \
        -e ENV_TYPE=production -e TAGS=webpack \
        -e ANSIBLE_VAULT_PASS=${{secrets.ANSIBLE_VAULT_PASS}} corpora-deploy
