name: Deploy Production

on:
  push:
    branches:
      - tumu
    paths-ignore:
      - "corpora/vue_frontend/**"
      - "corpora-deploy/**"
      - "README.md"
      - "*.md"

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - uses: aws-actions/amazon-ecr-login@v1
    - run: |
        docker build ./corpora-deploy -t corpora-deploy --file ./corpora-deploy/gitactions.Dockerfile
    - name: Deploy production 
      run: |
        docker run --entrypoint /deploy/scripts/deploy.sh \
        -e ENV_TYPE=production -e TAGS=deploy-django \
        -e ANSIBLE_VAULT_PASS=${{secrets.ANSIBLE_VAULT_PASS}} corpora-deploy:latest
